### PR TITLE
Fix Resistor Bugs

### LINKED ISSUE #48: Invalid resistor colors shouldn't throw exceptions
1) Make resistor: Black, Red, Gold, Not Present
2) Change fourth band to Gold
Expected: Notification that the resistor has no value
Actual: Crash

Having the value return a type that's handleable such as null would be preferrable

### LINKED ISSUE #49: ResistorColorEntry.hasTolerance is broken
It should check toleranceInPercent, not value.

### PR DESCRIPTION
**Pull request by beckbria**
Fixes #48.
Fixes #49.

Also removes the +/- from the tolerance output since that was getting escaped in the frontend and wasn't useful.

### CODE REVIEW

File: src/Resistor/Resistor.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ class Resistor {
     for (let i = 0; i < (colors.length - 1); ++i) {
       const currentColor = colors[i];
       if (currentColor.value === undefined) {
-        throw new Error('Invalid value color');
+        return 'Invalid';
```
Comment (kfarnung) [inline src/Resistor/Resistor.ts]: Not a fan of special strings like this.  I'd say return `-1` or `null` if possible.  It should be up to the UI to determine what string to show.

It also seems like normally you're returning a number, so it's weird to also return a string down this path.

Comment (beckbria) [reply src/Resistor/Resistor.ts]: Changed to -1
